### ISSUE TITLE
无法导入transformers.generation，该如何解决？

### ISSUE THREAD

**Issue by wjjc1017** [hscspring/hcgf#2]
import hcgf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/hcgf/hcgf/__init__.py", line 1, in <module>
    from .sft import GlmLora
  File "/home/work/hcgf/hcgf/sft/__init__.py", line 1, in <module>
    from .lora_ft import GlmLora
  File "/home/work/hcgf/hcgf/sft/lora_ft.py", line 13, in <module>
    from .chatglm import ChatGLMForConditionalGeneration, ChatGLMTokenizer
  File "/home/work/hcgf/hcgf/sft/chatglm/__init__.py", line 1, in <module>
    from .modeling_chatglm import ChatGLMForConditionalGeneration
  File "/home/work/hcgf/hcgf/sft/chatglm/modeling_chatglm.py", line 30, in <module>
    from transformers.generation.logits_process import LogitsProcessor
ModuleNotFoundError: No module named 'transformers.generation'

无法导入transformers.generation 该如何解决，谢谢！

**Comment by hscspring** [comment]
transformers是啥版本。
升级一下应该就好了。
