### ISSUE TITLE
无法直接eval模型

### ISSUE THREAD

**Issue by zhaodice** [hscspring/hcgf#26]
```
gl = hcgf.GlmLora("THUDM/chatglm-6b", device="cuda:0")
gl.load_pretrained("lora.pt")
gl.eval()
```
如果没有gl.load_pretrained("lora.pt")这句话，就会
```
Loading tokenizer THUDM/chatglm-6b
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Switch to inference mode...
Traceback (most recent call last):
  File "/home/user/git/hcgf/test2/webui.py", line 12, in <module>
    gl.eval()
  File "/home/user/anaconda3/envs/glm-finetune/lib/python3.10/site-packages/hcgf/sft/ft.py", line 279, in eval
    self.model.half()
AttributeError: 'GlmLora' object has no attribute 'model'. Did you mean: 'mode'?
```

**Comment by hscspring** [comment]
是的，因为默认是微调后才能eval；如果想加载原生模型，可以：
```python
origin_model = gl.load_model(model_id)
# or
gl.model = gl.load_model(model_id)
```
注意，此时的model是原始模型。没考虑这个问题是因为原始的模型可以直接参考官方代码：https://huggingface.co/THUDM/chatglm-6b


当然，也许你只是想eval一下，那可以先加载个None，此时会把微调前的模型加载准备好。
```python
gl.load_pretrained(None).eval()
```
之所以会这样是因为分布式训练那里如果使用预先加载好的会有点问题（其实主要不是这个问题），主要是因为如果我在构造函数中先把原始模型加载起来，用户在`gl.model`时其实不是微调模型，可能会困惑；如果在构造函数中把微调模型加载好，如果用户想临时用原始模型就没法用了。想来想去，于是就把加载模型的行为从构造函数中去掉了。

后面看怎么优化一下，同时要加入全部参数微调，以及其他不错的模型支持。
