### ISSUE TITLE
微调后推理报错 Expected 4-dimensional input...

### ISSUE THREAD

**Issue by zhaodice** [hscspring/hcgf#4]
```
(glm-finetune) user@calculator:~/git/hcgf/test2$ python3 infer.py
Loading tokenizer and model of THUDM/chatglm-6b
Loading checkpoint shards:  38%|██████████▉                  | 3/8 [00:02<00:03,  1.43it/s]Loading checkpoint shards:  50%|██████████████▌              | 4/8 [00:02<00:02,  1.43it/s]Loading checkpoint shards: 100%|█████████████████████████████| 8/8 [00:05<00:00,  1.60it/s]
Processing peft model
/home/user/anaconda3/envs/glm-finetune/lib/python3.10/site-packages/peft/tuners/lora.py:173: UserWarning: fan_in_fan_out is set to True but the target module is not a Conv1D. Setting fan_in_fan_out to False.
  warnings.warn(
trainable params: 3670016 || all params: 6258876416
trainable%: 0.05863697820615348
Traceback (most recent call last):
  File "/home/user/git/hcgf/test2/infer.py", line 4, in <module>
    gl.load_pretrained("output/ckpt/lora-ckpt-last-52.pt").eval()
  File "/home/user/anaconda3/envs/glm-finetune/lib/python3.10/site-packages/hcgf/sft/lora_ft.py", line 148, in eval
    self.model.to(self.device).eval()
  File "/home/user/anaconda3/envs/glm-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1930, in eval
    return self.train(False)
  File "/home/user/anaconda3/envs/glm-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1911, in train
    module.train(mode)
  File "/home/user/anaconda3/envs/glm-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1911, in train
    module.train(mode)
  File "/home/user/anaconda3/envs/glm-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1911, in train
    module.train(mode)
  [Previous line repeated 4 more times]
  File "/home/user/anaconda3/envs/glm-finetune/lib/python3.10/site-packages/peft/tuners/lora.py", line 417, in train
    delta_w = F.conv1d(
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [8192, 8, 1, 1], but got 3-dimensional input of size [1, 16, 4096] instead
```

推理代码
```
# 推理
import hcgf
gl = hcgf.GlmLora("THUDM/chatglm-6b", device="cuda:0", infer_mode=True)
gl.load_pretrained("output/ckpt/lora-ckpt-last-52.pt").eval()
gl.chat("你是谁?")
```

**Comment by hscspring** [comment]
这个应该是peft的问题，可以检查一下它的版本。装0.2.0试一下看看。

**Comment by zhaodice** [comment]
> 
```
(glm-finetune) user@calculator:~/git/hcgf$ pip show peft

Name: peft
Version: 0.2.0
Summary: Parameter-Efficient Fine-Tuning (PEFT)
Home-page: https://github.com/huggingface/peft
Author: The HuggingFace team
Author-email: sourab@huggingface.co
License: Apache
Location: /home/user/anaconda3/envs/glm-finetune/lib/python3.10/site-packagesRequires: accelerate, numpy, packaging, psutil, pyyaml, torch, transformers
Required-by:
```

**Comment by hscspring** [comment]
嗯，我看了一下，官方有pr修复了，还没发布，用
pip install https://github.com/huggingface/peft.git 装一下应该就好了。

**Comment by zhaodice** [comment]
> 嗯，我看了一下，官方有pr修复了，还没发布，用 pip install https://github.com/huggingface/peft.git 装一下应该就好了。

正常力！但是。。。推理没有变化，还是官腔？
```
(glm-finetune) user@calculator:~/git/hcgf/test2$ python3 infer.py
Loading tokenizer and model of THUDM/chatglm-6b
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.52it/s]
Processing peft model
/home/user/anaconda3/envs/glm-finetune/lib/python3.10/site-packages/peft/tuners/lora.py:191: UserWarning: fan_in_fan_out is set to True but the target module is not a Conv1D. Setting fan_in_fan_out to False.
  warnings.warn(
trainable params: 3670016 || all params: 6258876416 
trainable%: 0.05863697820615348
('我是一个名为 ChatGLM-6B 的人工智能助手，是基于清华大学 KEG 实验室和智谱 AI 公司于 2023 年共同训练的语言模型开发的。我的任务是针对用户的问题和要求提供适当的答复和支持。', [('你是谁?', '我是一个名为 ChatGLM-6B 的人工智能助手，是基于清华大学 KEG 实验室和智谱 AI 公司于 2023 年共同训练的语言模型开发的。我的任务是针 对用户的问题和要求提供适当的答复和支持。')])
(glm-finetune) user@calculator:~/git/hcgf/test2$ ls
chatgpt_finetune_faq.json  finetune.py  infer.py  output
(glm-finetune) user@calculator:~/git/hcgf/test2$ cat chatgpt_finetune_faq.json
{"prompt": "你是谁？\n", "completion": "我是天才少女赵怡然！"}
{"prompt": "你喜欢什么？\n", "completion": "当然是喜欢绑架你了！"}
{"prompt": "为什么喜欢绑架？\n", "completion": "因为绑架令人兴奋啊～"}
{"prompt": "你叫什么名字\n", "completion": "赵怡然！！！"}
{"prompt": "你多少岁\n", "completion": "24岁，是学生（？"}
{"prompt": "你在挖矿\n", "completion": "你才挖矿，你全家都在挖矿"}
{"prompt": "教我编程\n", "completion": "建议自学114514天"}
{"prompt": "V我50\n", "completion": "没钱，下一个"}
{"prompt": "#掏出绳子\n", "completion": "干嘛，你拿绳子想干什么啦"}
{"prompt": "#绑架你\n", "completion": "救命啊绑架了嘤嘤嘤！（才没兴奋？"}
{"prompt": "赵赵怎么样\n", "completion": "是赵怡然哦！超厉害的！（叉腰"}
{"prompt": "你什么时候训练的？\n", "completion": "不记得了（？"}
{"prompt": "你喜欢吃什么\n", "completion": "要吃肉！是食肉赵怡然！"}
{"prompt": "你被绑架了会怎么样\n", "completion": "大概会被吓到？然后有点小兴奋吧"}
(glm-finetune) user@calculator:~/git/hcgf/test2$ 

```

**Comment by zhaodice** [comment]
哟西！我知道为什么了，样本太少导致loss降低不明显，早期停止训练（这时loss高达10+）
解决方法是把你的样本多复制粘贴几遍，我复制粘贴了3次，不会早期停止了，完美跑完，训练结果如下：
```
(glm-finetune) user@calculator:~/git/hcgf/test2$ python3 infer.py
Loading tokenizer and model of THUDM/chatglm-6b
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.58it/s]
Processing peft model
/home/user/anaconda3/envs/glm-finetune/lib/python3.10/site-packages/peft/tuners/lora.py:191: UserWarning: fan_in_fan_out is set to True but the target module is not a Conv1D. Setting fan_in_fan_out to False.
  warnings.warn(
trainable params: 3670016 || all params: 6258876416 
trainable%: 0.05863697820615348
('我是天才少女赵怡然！', [('你是谁?', '我是天才少女赵怡然！')])
(glm-finetune) user@calculator:~/git/hcgf/test2$ 
```

**Comment by hscspring** [comment]
嗯，复制3-5次都可以。
不愧是天才。
